name: Deploy Preview

on:
  pull_request:

jobs:
  # Add bugster integration after your deployment job
  trigger-bugster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Notify Bugster (success deployment)
        uses: Bugsterapp/bugster-action@v1
        with:
          bugster_api_key: ${{ secrets.BUGSTER_API_KEY }}
          organization_id: "org_35I9WtAnQuIna70rU8j5wWFMwhZ"
          project_id: "cerebryx-1763164739"
          environment_url: "https://cerebryx.vercel.app/"